// <auto-generated />
namespace STV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idmaterial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idmaterial));
        
        string IMigrationMetadata.Id
        {
            get { return "201607121726059_idmaterial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
