// <auto-generated />
namespace STV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idmaterial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idmaterial2));
        
        string IMigrationMetadata.Id
        {
            get { return "201607121735169_idmaterial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
